Homework 1. Surname: Ermolovich
CandiedDisc192/spbu_python pull request #2
Opened 2023-09-14 17:42 UTC by CandiedDisc192

2023-09-14 19:56 UTC, SpirinEgor requested changes

2023-09-14 19:56 UTC, SpirinEgor commented on 1.py
> +        print("{arg}^4 + {arg}^3 + {arg}^2 + {arg} + 1 = {ans}".format(arg=int(x) if int(x) == x else x,
1. Лучше f-строки использовать в таких кейсах. Будет более аккуратный и понятный код
2. Что за странный if и зачем он нужен?

2023-09-14 19:56 UTC, SpirinEgor commented on 2.py
> +def get_dot_product(vector1, vector2):
Вообще это `scalar_product`

2023-09-14 19:56 UTC, SpirinEgor commented on 2.py
> +            transposed_matrix[ci][ri] = matrix[ri][ci]
А одним генератором списка сможешь?

2023-09-14 19:56 UTC, SpirinEgor commented on 2.py
> +            res[ri][ci] = matrix1[ri][ci] + matrix2[ri][ci]
И здесь можно просто сразу генератором все посчитать

2023-09-14 19:56 UTC, SpirinEgor commented on 2.py
> +                product[ri][ci] += matrix1[ri][ti] * matrix2[ti][ci]
А вот тут можно красиво решить через транспонирование и скалярное произведение

2023-09-14 19:56 UTC, SpirinEgor commented on 2.py
> +if __name__ == "__main__":
Очень большой if, его надо разбивать на части и выносить в отдельные функции

2023-09-14 19:56 UTC, SpirinEgor commented on 3.py
> +    file.close()
Давай для wc сделаем ленивое чтение файла. Вдруг он большой и не помещается в память. Ну то есть надо читать его построчно и что-то делать, а не сразу весь целиком

2023-09-14 19:56 UTC, SpirinEgor commented on 3.py
> +        result += str(len(lines)) + " "
Кажется не лучше способ возвращать результат. Если что-то не считается, то будет 2 или 3 числа через пробел, как потом понять к чему они относятся?) Пусть возвращается словарь, где ключ это что считалось и значение сколько получилось

2023-09-14 19:56 UTC, SpirinEgor commented on 3.py
> +    print(result[:-1])
Ну и пусть функция только считает, выводится будет в отдельном месте, где вся работа с интерфейсом идет

2023-09-14 19:56 UTC, SpirinEgor commented on 3.py
> +    file.close()
Круто, что объединил head и tail. Оставим как есть тогда, без ленивого чтения для head.
Но вот подобная конструкция красиво записывается
```python
with open(file_name, "r") as f_in:
    lines = f_in.readlines()
```

2023-09-14 19:56 UTC, SpirinEgor commented on 3.py
> +        print(line.rstrip())
Опять же, логика в одном месте, принты в другом месте

2023-09-14 19:56 UTC, SpirinEgor commented on 3.py
> +    for line in lines if head else lines[len_lines - n:]:
Цикл тоже перегружен, давай для tail просто развернем лист линий и просто пройдем n итераций по нему

2023-09-14 19:56 UTC, SpirinEgor commented on 3.py
> +def head_or_tail_c(file_name, head, c):
Тут все замечания аналогичны предыдущей функции

2023-09-14 19:56 UTC, SpirinEgor commented on 3.py
> +        for symbol in line if head else line[::-1]:
А зачем нам по символам идти? Можно же всю строку заенкодить и от нее либо часть байтов взять, либо всю

2023-09-14 20:07 UTC, CandiedDisc192 commented on 1.py
> +        print("{arg}^4 + {arg}^3 + {arg}^2 + {arg} + 1 = {ans}".format(arg=int(x) if int(x) == x else x,
Я сделал if чтобы целые числа выводились без лишей точки

2023-09-14 20:09 UTC, CandiedDisc192 commented on 1.py
> +        print("{arg}^4 + {arg}^3 + {arg}^2 + {arg} + 1 = {ans}".format(arg=int(x) if int(x) == x else x,
> 2. Что за странный if и зачем он нужен?

If чтобы целые числа выводились без лишней точки

2023-09-16 10:24 UTC, SpirinEgor approved these changes

2023-09-16 10:24 UTC, SpirinEgor commented on 1.py
> +    try:
Не пиши такие try, они абсолютно бесполезны в данном случае. Лучше уж никак, чем криво

2023-09-16 10:24 UTC, merged