Practice 2. Task 1. Ermolovich
CandiedDisc192/spbu_python pull request #4
Opened 2023-09-22 11:35 UTC by CandiedDisc192

2023-10-04 19:26 UTC, toadharvard requested changes

2023-10-04 19:26 UTC, toadharvard commented on src/practices/practice3/task1.py
> +    order.sort()
Сохраняй пары (numerator, denominator) в список, а потом сортируй по key

У тебя тут смешано представление дробей (вывод для пользователя) и сами дроби

2023-10-04 19:28 UTC, toadharvard commented
Коммиты не очень https://www.conventionalcommits.org/en/v1.0.0/

А еще не стоит мержить мейн в твою ветку, это как минимум странно, а как максимум есть rebase

2023-10-10 17:28 UTC, SpirinEgor approved these changes

2023-10-12 17:31 UTC, toadharvard approved these changes

2023-10-12 17:32 UTC, merged