Practice 2. Task 2. Ermolovich
CandiedDisc192/spbu_python pull request #5
Opened 2023-09-22 12:10 UTC by CandiedDisc192

2023-10-04 19:39 UTC, toadharvard requested changes

2023-10-04 19:39 UTC, toadharvard commented on src/practices/practice3/task2.py
> +    bulls_cows = [0, 0]
Лучше 2 переменных, потому что непонятно, кто есть кто без чтения дальнейшего кода

2023-10-04 19:39 UTC, toadharvard commented on src/practices/practice3/task2.py
> +        current_res = get_bulls_and_cows_current_res(guess, random_value)
current_bulls, current_cows =  get_bulls_and_cows_current_res(guess, random_value)

2023-10-04 19:39 UTC, toadharvard commented on src/practices/practice3/task2.py
> +        guess = input(f"{current_guess_num}. Введите ваше предположение: ")
Почему разрешено предсказание строк, а не только чисел?

2023-10-15 11:28 UTC, SpirinEgor requested changes

2023-10-15 11:28 UTC, SpirinEgor commented on src/practices/practice3/task2.py
> +    digits_count = get_digits_count()
Вот все, что ниже, надо в функцию обернуть, `game` или `main`...

2023-10-15 11:43 UTC, SpirinEgor approved these changes

2023-10-16 20:45 UTC, toadharvard approved these changes

2023-10-16 20:45 UTC, merged